- service: twitter
  username: rattermeyer
  url: http://www.twitter.com/rattermeyer

- service: google+
  username: richardattermeyer
  url: http://www.google.com/+RichardAttermeyer

- service: github
  username: rattermeyer
  url: http://www.github.com/rattermeyer

- service: stackoverflow
  username: rattermeyer
  url: http://stackoverflow.com/users/1838932/rattermeyer

- service: facebook
  username: rattermeyer
  url: http://www.facebook.com/rattermeyer

- service: xing
  username: richard_attermeyer
  url: http://www.xing.com/profile/Richard_Attermeyer

- service: lanyrd
  username: richard_attermeyer
  url: http://lanyrd.com/profile/richard_attermeyer

- service: email
  username: richard.attermeyer
  url: mailto:richard.attermeyer@gmail.com

